name: record-linkage
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel=6.30
  - ipywidgets=8.1
  - matplotlib=3.10
  - pandas=2.2
  - pip=25.2
  - setuptools>=70.0.0
  - wheel>=0.44.0
  - pip:
      - linktransformer